# Generated by Django 5.0.14 on 2026-08-13 09:11

import django.db.models.deletion
import schedule.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('schedule', '0001_initial'), ('schedule', '0002_subscription'), ('schedule', '0003_feedback'), ('schedule', '0005_conspect'), ('schedule', '0006_auth_students'), ('schedule', '0008_conspect_group'), ('schedule', '0009_alter_feedback_options_alter_subscription_options_and_more')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Группа')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('name', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Преподаватель')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('name', models.CharField(db_index=True, max_length=250, unique=True, verbose_name='Дисциплина')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('day_of_week', models.CharField(blank=True, default='', max_length=20, verbose_name='День недели')),
                ('pair_number', models.PositiveSmallIntegerField(verbose_name='Пара')),
                ('subgroup', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Подгруппа')),
                ('room', models.CharField(blank=True, default='', max_length=50, verbose_name='Аудитория')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='schedule.group', verbose_name='Группа')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='schedule.teacher', verbose_name='Преподаватель')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='schedule.subject', verbose_name='Дисциплина')),
            ],
            options={
                'ordering': ['date', 'pair_number', 'subgroup'],
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
                'indexes': [models.Index(fields=['date', 'group'], name='schedule_le_date_e86dd1_idx'), models.Index(fields=['date', 'teacher'], name='schedule_le_date_3fe2e2_idx'), models.Index(fields=['date', 'day_of_week'], name='schedule_le_date_304870_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConspectSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Предмет')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Предмет (конспекты)',
                'verbose_name_plural': 'Предметы (конспекты)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConspectDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата занятия')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='schedule.conspectsubject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Дата (конспекты)',
                'verbose_name_plural': 'Даты (конспекты)',
                'ordering': ['-date'],
                'unique_together': {('subject', 'date')},
            },
        ),
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('limit', models.PositiveSmallIntegerField(default=30, verbose_name='Лимит студентов')),
                ('used', models.PositiveSmallIntegerField(default=0, verbose_name='Использовано')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_codes', to='schedule.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Инвайт-код',
                'verbose_name_plural': 'Инвайт-коды',
                'ordering': ['group', 'code'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='schedule.group', verbose_name='Группа')),
                ('invite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.invitecode', verbose_name='Инвайт-код')),
            ],
            options={
                'verbose_name': 'Профиль студента',
                'verbose_name_plural': 'Профили студентов',
            },
        ),
        migrations.CreateModel(
            name='Conspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Имя автора')),
                ('file', models.FileField(upload_to=schedule.models.conspect_upload_path, verbose_name='Файл')),
                ('file_type', models.CharField(choices=[('conspect', 'Конспект'), ('hw', 'Домашнее задание'), ('other', 'Другое')], default='conspect', max_length=10, verbose_name='Тип')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='Описание (необязательно)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('conspect_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conspects', to='schedule.conspectdate', verbose_name='Дата')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conspects', to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт автора')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conspects', to='schedule.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Конспект',
                'verbose_name_plural': 'Конспекты',
                'ordering': ['author_name'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('bug', 'Bug'), ('idea', 'Idea'), ('other', 'Other')], default='other', max_length=10, verbose_name='Category')),
                ('text', models.TextField(verbose_name='Message')),
                ('contact', models.CharField(blank=True, default='', max_length=100, verbose_name='Contact')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='Read')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(db_index=True, verbose_name='Telegram chat_id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='schedule.group', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'unique_together': {('chat_id', 'group')},
            },
        ),
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('bug', 'Баг / ошибка'), ('idea', 'Идея / предложение'), ('other', 'Другое')], default='other', max_length=10, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Контакт (необязательно)'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='schedule.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
