# Generated by Django 5.0.14 on 2026-09-01 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_alter_feedback_options_alter_group_options_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='lesson',
            new_name='schedule_le_date_e86dd1_idx',
            old_name='lesson_date_group_idx',
        ),
        migrations.RenameIndex(
            model_name='lesson',
            new_name='schedule_le_date_3fe2e2_idx',
            old_name='lesson_date_teacher_idx',
        ),
        migrations.RenameIndex(
            model_name='lesson',
            new_name='schedule_le_date_304870_idx',
            old_name='lesson_date_dow_idx',
        ),
        migrations.RemoveField(
            model_name='group',
            name='slug',
        ),
    ]
