# Generated by Django 5.0.14 on 2026-09-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_alter_feedback_options_alter_group_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=120, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Счётчик просмотров',
                'verbose_name_plural': 'Счётчики просмотров',
            },
        ),
        migrations.RenameIndex(
            model_name='lesson',
            new_name='schedule_le_date_e86dd1_idx',
            old_name='lesson_date_group_idx',
        ),
        migrations.RenameIndex(
            model_name='lesson',
            new_name='schedule_le_date_3fe2e2_idx',
            old_name='lesson_date_teacher_idx',
        ),
        migrations.RenameIndex(
            model_name='lesson',
            new_name='schedule_le_date_304870_idx',
            old_name='lesson_date_dow_idx',
        ),
    ]
